language: python
python:
  - 3.6.5
install:
  - pip install --upgrade pip
  - pip install -q Django==2.0
  - pip install -r requirements.txt
script:
  - make test
services:
  - rabbitmq
  - postgresql
